In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from NeuralNetwork import *
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('../../../ML-Project/assests/feature_selected_voice_data.csv')

In [3]:
df = df.sample(frac=1)
df

meanfreq        sd    median       Q25       Q75       IQR       kurt  \
437   0.195052  0.059411  0.215385  0.136032  0.244291  0.108259   4.605497   
2783  0.187616  0.036183  0.180285  0.168319  0.210199  0.041880  15.760113   
2557  0.197505  0.027834  0.196589  0.187430  0.208364  0.020935  16.132526   
703   0.149878  0.061349  0.158791  0.095605  0.197198  0.101593  10.295662   
610   0.156414  0.076329  0.147649  0.103841  0.228079  0.124238   5.854601   
...        ...       ...       ...       ...       ...       ...        ...   
3049  0.196159  0.044349  0.202957  0.192696  0.216348  0.023652  17.390557   
987   0.195705  0.060049  0.225139  0.127320  0.246876  0.119556   6.272353   
688   0.153817  0.058905  0.162708  0.102083  0.202292  0.100208  19.951360   
1571  0.158537  0.059210  0.137282  0.109580  0.215479  0.105899  15.317888   
404   0.195947  0.063271  0.214076  0.134329  0.253063  0.118734   4.016681   

        sp.ent       sfm      mode   meanfun    minfun   modindx   label  
437   0.920989  0.419248  0.232672  0.115489  0.039120  0.165980    male  
2783  0.861486  0.263261  0.168718  0.157005  0.047013  0.135204  female  
2557  0.807993  0.171635  0.192991  0.173714  0.047291  0.101709  female  
703   0.909933  0.447821  0.095398  0.099987  0.053763  0.654164    male  
610   0.969736  0.755512  0.124702  0.116346  0.021948  0.346695    male  
...        ...       ...       ...       ...       ...       ...     ...  
3049  0.851043  0.293635  0.204870  0.198551  0.084746  0.572368  female  
987   0.873643  0.290546  0.118004  0.118063  0.047151  0.094335    male  
688   0.896026  0.445363  0.099583  0.105999  0.089286  0.670115    male  
1571  0.920055  0.452015  0.110632  0.109522  0.045662  0.266656    male  
404   0.921747  0.461691  0.235342  0.119255  0.029197  0.082353    male  

[3168 rows x 14 columns]

In [4]:
df['label'].unique()

array(['male', 'female'], dtype=object)

In [5]:
x = df.drop('label' , axis=1)
# y = label_binarize(df['label'], classes=df['label'].unique())
y = []
for i in range(x.shape[0]):
    y.append(np.array([[1], [0]]) if df.iloc[i]['label']=='male' else np.array([[0],[1]]))
y = np.array(y)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [7]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2534, 13)
(634, 13)
(2534, 2, 1)
(634, 2, 1)


In [8]:
y_train[:10]

array([[[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [0]]])

### Neural Network

In [9]:
nn = NeuralNetwork(N=4, neuronInEachLayers=[13,128,64,2], lr=1e-2, 
                    activation='sigmoid', weightInitType='random', epochs=5, batchSize=128)

In [10]:
print(nn.a_values)

[array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]) array([[1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
      

In [11]:
nn.forwardPropagation(x_train.iloc[0])

array([[0.58321261],
       [0.41678739]])

In [12]:
print(nn.a_values)

[array([[ 1.        ],
        [ 0.23670287],
        [ 0.03574607],
        [ 0.24734694],
        [ 0.2244898 ],
        [ 0.25877551],
        [ 0.03428571],
        [10.97562374],
        [ 0.82321106],
        [ 0.18290227],
        [ 0.24857143],
        [ 0.18529739],
        [ 0.04705882],
        [ 0.11589147]]) array([[1.        ],
                               [0.95717233],
                               [0.93511584],
                               [0.19901081],
                               [0.15517582],
                               [0.11635786],
                               [0.74233681],
                               [0.95317519],
                               [0.06096682],
                               [0.20216327],
                               [0.947507  ],
                               [0.83930313],
                               [0.73565873],
                               [0.81017498],
                               [0.92363142],
                          

In [65]:
nn.weights_Θ[0].max()*np.sqrt(10)/np.sqrt(20)

0.2407165404814094

In [13]:
print(nn.weights_Θ[0].shape)
print(nn.weights_Θ[1].shape)
print(nn.weights_Θ[2].shape)
print(nn.epochs)
print(nn.lr)
print(nn.activation)

(128, 14)
(64, 129)
(2, 65)
5
0.01


In [14]:
nn.δ_values[3][1:]

array([[1.],
       [1.]])

In [15]:
nn.fit(x_train, y_train)

0 1 2 3 4 

In [16]:
y_pred = nn.predict(x_test)
y_pred_proba = nn.predict_proba(x_test)
print(nn.score(x_train, y_train))
print(nn.score(x_test, y_test))

0.5986582478295186
0.5899053627760252


In [17]:
for _ in y_pred_proba:
    print(_[:,0])

[0.56283497 0.43716503]
[0.46601756 0.53398244]
[0.35794202 0.64205798]
[0.44133107 0.55866893]
[0.39711912 0.60288088]
[0.410281 0.589719]
[0.34415379 0.65584621]
[0.47957954 0.52042046]
[0.44915012 0.55084988]
[0.42007977 0.57992023]
[0.47049666 0.52950334]
[0.50631087 0.49368913]
[0.47945744 0.52054256]
[0.36975681 0.63024319]
[0.3599985 0.6400015]
[0.33503343 0.66496657]
[0.52579344 0.47420656]
[0.58442158 0.41557842]
[0.49459906 0.50540094]
[0.33294613 0.66705387]
[0.35092895 0.64907105]
[0.50232957 0.49767043]
[0.50689558 0.49310442]
[0.46523532 0.53476468]
[0.3534279 0.6465721]
[0.44344619 0.55655381]
[0.41349792 0.58650208]
[0.52490046 0.47509954]
[0.35402422 0.64597578]
[0.47533058 0.52466942]
[0.43416077 0.56583923]
[0.56926946 0.43073054]
[0.60746429 0.39253571]
[0.41753762 0.58246238]
[0.35687811 0.64312189]
[0.45826577 0.54173423]
[0.38411796 0.61588204]
[0.56399807 0.43600193]
[0.4019574 0.5980426]
[0.40905869 0.59094131]
[0.4554901 0.5445099]
[0.53901619 0.46098381]
[0.4

In [18]:
0 in y_pred[:,0]

True

In [19]:
y_pred[:,0]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,

In [20]:
print(y_pred_proba)

[[[0.56283497]
  [0.43716503]]

 [[0.46601756]
  [0.53398244]]

 [[0.35794202]
  [0.64205798]]

 ...

 [[0.44185657]
  [0.55814343]]

 [[0.3331917 ]
  [0.6668083 ]]

 [[0.39974439]
  [0.60025561]]]


In [21]:
y_test

array([[[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]],

       ...,

       [[0],
        [1]],

       [[0],
        [1]],

       [[0],
        [1]]])

In [22]:
y_test.argmax(axis=1)[:,0]

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,

In [23]:
x_test.iloc[-1]

meanfreq    0.148297
sd          0.076496
median      0.171785
Q25         0.070121
Q75         0.210849
IQR         0.140728
kurt        9.757131
sp.ent      0.943685
sfm         0.654823
mode        0.010919
meanfun     0.172746
minfun      0.028169
modindx     0.090308
Name: 2925, dtype: float64

In [24]:
nn.a_values[-1][1:]

array([[0.39974439],
       [0.60025561]])