In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from NeuralNetwork import *
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('../../../ML-Project/assests/feature_selected_voice_data.csv')

In [3]:
df = df.sample(frac=1)
df

meanfreq        sd    median       Q25       Q75        kurt    sp.ent  \
1032  0.204842  0.058805  0.220699  0.154978  0.257686    6.265021  0.922661   
2739  0.195080  0.040663  0.195166  0.172914  0.212781    6.170285  0.880661   
2071  0.139408  0.080712  0.147872  0.075334  0.191718   68.571873  0.957538   
2548  0.203962  0.034077  0.207763  0.189538  0.220686    9.933948  0.850812   
191   0.118850  0.077089  0.118976  0.047916  0.170477    8.721391  0.955491   
...        ...       ...       ...       ...       ...         ...       ...   
2705  0.215233  0.052964  0.227525  0.173047  0.263977    7.646105  0.897352   
530   0.133108  0.079635  0.128146  0.105080  0.183677  686.588177  0.875579   
688   0.153817  0.058905  0.162708  0.102083  0.202292   19.951360  0.896026   
2683  0.201464  0.047455  0.203636  0.161690  0.242356    3.273490  0.906194   
1713  0.235349  0.061951  0.255031  0.240735  0.266086   10.445064  0.832678   

           sfm      mode   meanfun    minfun   modindx   label  
1032  0.380896  0.268690  0.104783  0.047105  0.073683    male  
2739  0.252454  0.206755  0.146272  0.047291  0.160921  female  
2071  0.711622  0.120504  0.142514  0.016771  0.100225  female  
2548  0.238414  0.219030  0.169247  0.049741  0.142292  female  
191   0.715342  0.123539  0.098098  0.016807  0.251351    male  
...        ...       ...       ...       ...       ...     ...  
2705  0.341804  0.275193  0.165063  0.047714  0.128334  female  
530   0.459351  0.000000  0.090806  0.015656  0.000000    male  
688   0.445363  0.099583  0.105999  0.089286  0.670115    male  
2683  0.280811  0.261357  0.166031  0.056206  0.122048  female  
1713  0.247794  0.260749  0.209523  0.017204  0.133191  female  

[3168 rows x 13 columns]

In [4]:
df['label'].unique()

array(['male', 'female'], dtype=object)

In [5]:
x = df.drop('label' , axis=1)
# y = label_binarize(df['label'], classes=df['label'].unique())
y = []
for i in range(x.shape[0]):
    y.append(np.array([[1], [0]]) if df.iloc[i]['label']=='male' else np.array([[0],[1]]))
y = np.array(y)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [7]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2534, 12)
(634, 12)
(2534, 2, 1)
(634, 2, 1)


In [8]:
y_train[:10]

array([[[1],
        [0]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[0],
        [1]]])

### Neural Network

In [9]:
nn = NeuralNetwork(4, [12,32,16,2], 1e-5, 'sigmoid', 'normal', 100, 100)

In [10]:
print(nn.a_values)

[array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]) array([[1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                    

In [11]:
nn.forwardPropagation(x_train.iloc[0])

array([[0.07076013],
       [0.92923987]])

In [12]:
# nn.backwardPropagation(np.array([0,1]))

In [13]:
print(nn.a_values)

[array([[1.        ],
        [0.19742573],
        [0.05482934],
        [0.19618684],
        [0.15641563],
        [0.24183031],
        [9.98868658],
        [0.8941567 ],
        [0.17896293],
        [0.        ],
        [0.13630201],
        [0.04383562],
        [0.30572852]]) array([[1.00000000e+00],
                              [5.35320009e-01],
                              [9.90282493e-01],
                              [9.99997697e-01],
                              [9.95042244e-01],
                              [1.94345770e-05],
                              [1.18838485e-03],
                              [3.75481628e-01],
                              [9.99997383e-01],
                              [9.99560838e-01],
                              [5.91941134e-01],
                              [9.73633676e-05],
                              [3.30899114e-03],
                              [1.00000000e+00],
                              [9.15341229e-01],
                

In [14]:
print(nn.weights_Θ[0].shape)
print(nn.weights_Θ[1].shape)
print(nn.weights_Θ[2].shape)
print(nn.epochs)
print(nn.lr)
print(nn.activation)

(32, 13)
(16, 33)
(2, 17)
100
1e-05


In [15]:
nn.δ_values[3][1:]

array([[1.],
       [1.]])

In [16]:
nn.fit(x_train, y_train)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [17]:
print(nn.a_values)

[array([[1.        ],
        [0.24704068],
        [0.03804082],
        [0.25663126],
        [0.23793627],
        [0.26852807],
        [8.38686837],
        [0.80084186],
        [0.16188801],
        [0.27235205],
        [0.19186437],
        [0.04883011],
        [0.14725379]]) array([[1.00000000e+00],
                              [4.64446666e-01],
                              [9.87499075e-01],
                              [9.99977202e-01],
                              [9.88661316e-01],
                              [8.70326620e-05],
                              [5.61631452e-03],
                              [4.25082972e-01],
                              [9.99988607e-01],
                              [9.98360662e-01],
                              [5.07709021e-01],
                              [2.57810791e-04],
                              [6.21852341e-03],
                              [9.99999995e-01],
                              [9.06129865e-01],
                

In [30]:
y_pred_proba = nn.predict_proba(x_test)
y_pred = nn.predict(x_test)
nn.score(x_test, y_train)

0.505130228887135

In [31]:
for _ in y_pred_proba:
    print(_)

[[0.07150557]
 [0.92849443]]
[[0.09816569]
 [0.90183431]]
[[0.05267256]
 [0.94732744]]
[[0.15423464]
 [0.84576536]]
[[0.15423782]
 [0.84576218]]
[[0.13526021]
 [0.86473979]]
[[0.07837792]
 [0.92162208]]
[[0.05554049]
 [0.94445951]]
[[0.09426354]
 [0.90573646]]
[[0.11990945]
 [0.88009055]]
[[0.071103]
 [0.928897]]
[[0.09558436]
 [0.90441564]]
[[0.07612146]
 [0.92387854]]
[[0.06202679]
 [0.93797321]]
[[0.10160296]
 [0.89839704]]
[[0.07956113]
 [0.92043887]]
[[0.0859125]
 [0.9140875]]
[[0.06276011]
 [0.93723989]]
[[0.07281984]
 [0.92718016]]
[[0.06556489]
 [0.93443511]]
[[0.06252595]
 [0.93747405]]
[[0.06540891]
 [0.93459109]]
[[0.0508343]
 [0.9491657]]
[[0.05034021]
 [0.94965979]]
[[0.07599826]
 [0.92400174]]
[[0.05334545]
 [0.94665455]]
[[0.12248435]
 [0.87751565]]
[[0.05156972]
 [0.94843028]]
[[0.10624245]
 [0.89375755]]
[[0.07175036]
 [0.92824964]]
[[0.05195282]
 [0.94804718]]
[[0.07462446]
 [0.92537554]]
[[0.09014445]
 [0.90985555]]
[[0.0702468]
 [0.9297532]]
[[0.05085162]
 [0.949148

In [36]:
0 in y_pred[:,0]

False

In [37]:
print(y_pred_proba)

[[[0.07150557]
  [0.92849443]]

 [[0.09816569]
  [0.90183431]]

 [[0.05267256]
  [0.94732744]]

 ...

 [[0.05366582]
  [0.94633418]]

 [[0.04641475]
  [0.95358525]]

 [[0.06627477]
  [0.93372523]]]


In [38]:
y_test

array([[[0],
        [1]],

       [[0],
        [1]],

       [[0],
        [1]],

       ...,

       [[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]]])

In [39]:
y_test.argmax(axis=1)[:,0]

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,

In [24]:
x_test.iloc[-1]

meanfreq    0.212031
sd          0.034822
median      0.209666
Q25         0.193196
Q75         0.230143
kurt        9.425050
sp.ent      0.854942
sfm         0.197909
mode        0.205660
meanfun     0.189002
minfun      0.049587
modindx     0.099966
Name: 2292, dtype: float64

In [25]:
nn.a_values[-1][1:]

array([[0.06604836],
       [0.93395164]])