In [1]:
import numpy as np
import pandas as pd
from WeightInitialization import *

In [2]:
a = np.array([1,-1,2,-3,4])
b = np.zeros(shape=a.shape)

In [3]:
np.vectorize(lambda x: 1 if x>=0 else 0)(a)

array([1, 0, 1, 0, 1])

In [4]:
getNeuralNetworkWeights(4, [3,2,4,1], 'random')

c:\Users\khush\Desktop\ML-Assignments\Assignment-3\Section-B\WeightInitialization.py:17: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(weights)


array([array([[-0.93211938,  0.74321852, -0.78338846,  0.55502887],
              [ 0.72961375,  0.61752687,  0.80286394,  0.96158049]]),
       array([[ 0.01792653, -0.79663572, -0.10500364],
              [-0.96262964,  0.16675427, -0.13711844],
              [ 0.24812759,  0.3253787 , -0.06637799],
              [-0.92364839,  0.89008053, -0.42446743]]),
       array([[-0.29736268,  0.20490391,  0.87069422,  0.92184833, -0.77060341]])],
      dtype=object)

In [5]:
x = np.array([1.3, 5.1, 2.2, 0.7, 1.1])
y = np.exp(x)

softmax = y/np.sum(y)
softmax

array([0.02019046, 0.90253769, 0.04966053, 0.01108076, 0.01653055])

In [6]:
a

array([ 1, -1,  2, -3,  4])

In [7]:
-np.outer(a, a)

array([[ -1,   1,  -2,   3,  -4],
       [  1,  -1,   2,  -3,   4],
       [ -2,   2,  -4,   6,  -8],
       [  3,  -3,   6,  -9,  12],
       [ -4,   4,  -8,  12, -16]])

In [8]:
np.diag(a.flatten())

array([[ 1,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0],
       [ 0,  0,  2,  0,  0],
       [ 0,  0,  0, -3,  0],
       [ 0,  0,  0,  0,  4]])

In [9]:
D = -np.outer(a, a) + np.diag(a.flatten())
D   

array([[  0,   1,  -2,   3,  -4],
       [  1,  -2,   2,  -3,   4],
       [ -2,   2,  -2,   6,  -8],
       [  3,  -3,   6, -12,  12],
       [ -4,   4,  -8,  12, -12]])

In [10]:
b[-2] = 10
b.argmax() + 1

4

In [11]:
c = np.array([[1,2,3,4],
              [9,2,66,7],
              [0,1,0,0]])
d = pd.DataFrame(c)

In [12]:
np.argmax(c, axis=1) + 1

array([4, 3, 2], dtype=int64)

In [13]:
arr = np.array([np.array([[1,2,3]]), np.array([[1,2,4],[1,0,1]])])

C:\Users\khush\AppData\Local\Temp\ipykernel_32616\1515316192.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([np.array([[1,2,3]]), np.array([[1,2,4],[1,0,1]])])


In [14]:
a2 = arr.copy()


In [38]:
a = np.array([[1,2,3,4]])
a.T

array([[1],
       [2],
       [3],
       [4]])

In [40]:
x = np.zeros(shape=(5,1))
x[1:] = a.T
x[1:].shape

(4, 1)

In [4]:
for i in range(0, 110, 20):
    print([j for j in range(i,i+20)])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]
[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
[60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]
[80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]


In [9]:
import numpy as np
z = np.array([[1],[2],[3],[-1]])
np.vectorize(lambda x: 1 if x >= 0 else 0)(z)

array([[1],
       [1],
       [1],
       [0]])

In [6]:
import numpy as np

y = np.array([[1,2,1,0], [2,1,3,1]])
p = np.array([[0.1,0.2,0.3,0.4], [0.3,0.3,0.2,0.2]])
loss = -y*np.log2(p)
loss

array([[ 3.32192809,  4.64385619,  1.73696559, -0.        ],
       [ 3.47393119,  1.73696559,  6.96578428,  2.32192809]])