In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from NeuralNetwork import *
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('../../../ML-Project/assests/feature_selected_voice_data.csv')

In [3]:
df = df.sample(frac=1)
df

meanfreq        sd    median       Q25       Q75       IQR        kurt  \
1842  0.180534  0.041912  0.188904  0.165251  0.201050  0.035799    9.109723   
207   0.168305  0.073634  0.191780  0.119088  0.220456  0.101368    6.069666   
40    0.171401  0.068428  0.145322  0.131202  0.246113  0.114911   13.726135   
2839  0.233652  0.032380  0.234030  0.223582  0.249910  0.026328   12.049914   
913   0.196337  0.058613  0.223013  0.137756  0.245897  0.108141    8.509636   
...        ...       ...       ...       ...       ...       ...         ...   
249   0.120008  0.086559  0.123758  0.011895  0.195131  0.183235  815.837002   
922   0.195220  0.070485  0.226528  0.136111  0.256667  0.120556    4.455862   
2442  0.214634  0.037498  0.220000  0.195238  0.241905  0.046667    5.324087   
2406  0.227865  0.035049  0.233333  0.213522  0.247862  0.034340    7.642660   
331   0.158009  0.061591  0.177004  0.101898  0.208847  0.106949    9.489748   

        sp.ent       sfm      mode   meanfun    minfun   modindx   label  
1842  0.857857  0.323957  0.193059  0.174824  0.017877  0.287212  female  
207   0.953991  0.631997  0.016863  0.120378  0.015920  0.282174    male  
40    0.893570  0.424254  0.137067  0.141183  0.015842  0.273221    male  
2839  0.794284  0.145934  0.234030  0.193572  0.047105  0.072418  female  
913   0.898985  0.376187  0.245897  0.131556  0.050740  0.046383    male  
...        ...       ...       ...       ...       ...       ...     ...  
249   0.824685  0.504159  0.000000  0.078679  0.016327  0.000000    male  
922   0.918393  0.516266  0.254236  0.144159  0.047059  0.128176    male  
2442  0.857046  0.239748  0.245238  0.167429  0.049231  0.102671  female  
2406  0.841557  0.200613  0.236855  0.175334  0.047384  0.065116  female  
331   0.906574  0.477634  0.103435  0.103890  0.050000  0.328244    male  

[3168 rows x 14 columns]

In [4]:
df['label'].unique()

array(['female', 'male'], dtype=object)

In [5]:
x = df.drop('label' , axis=1)
# y = label_binarize(df['label'], classes=df['label'].unique())
y = []
for i in range(x.shape[0]):
    y.append(np.array([[1], [0]]) if df.iloc[i]['label']=='male' else np.array([[0],[1]]))
y = np.array(y)

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [7]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2534, 13)
(634, 13)
(2534, 2, 1)
(634, 2, 1)


In [8]:
y_train[:10]

array([[[0],
        [1]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]]])

### Neural Network

In [9]:
nn = NeuralNetwork(N=6, neuronInEachLayers=[13,128,64,32,16,2], lr=1e-3, 
                    activation='sigmoid', weightInitType='normal', epochs=20, batchSize=10)

In [10]:
print(nn.a_values)

[array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]) array([[1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
      

In [11]:
nn.forwardPropagation(x_train.iloc[0])

array([[0.71775929],
       [0.28224071]])

In [12]:
print(nn.a_values[3])

[[1.        ]
 [0.50515473]
 [0.39396618]
 [0.49773069]
 [0.46419091]
 [0.41439829]
 [0.56863195]
 [0.48742562]
 [0.44982696]
 [0.5974418 ]
 [0.53628412]
 [0.68182476]
 [0.52966681]
 [0.68764005]
 [0.24353099]
 [0.42296299]
 [0.34955287]
 [0.57481842]
 [0.43708017]
 [0.52557509]
 [0.46660916]
 [0.5670375 ]
 [0.46131648]
 [0.5855889 ]
 [0.57786503]
 [0.47669722]
 [0.39856593]
 [0.38883258]
 [0.37123981]
 [0.75103073]
 [0.5088247 ]
 [0.47980792]
 [0.58898302]]


In [13]:
nn.weights_Θ[0].max()

0.31563303618688393

In [14]:
print(nn.weights_Θ[0].shape)
print(nn.weights_Θ[1].shape)
print(nn.weights_Θ[2].shape)
print(nn.epochs)
print(nn.lr)
print(nn.activation)

(128, 14)
(64, 129)
(32, 65)
20
0.001


In [15]:
nn.δ_values[3].shape

(33, 1)

In [16]:
nn.fit(x_train, y_train)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [17]:
y_pred = nn.predict(x_test)
y_pred_proba = nn.predict_proba(x_test)
print(nn.score(x_train, y_train))
print(nn.score(x_test, y_test))

0.5098658247829518
0.4605678233438486


In [18]:
nn.weights_Θ[2].max()

0.3374682697799051

In [19]:
for _ in y_pred_proba:
    print(_[:,0])

[0.49609863 0.50390137]
[0.49588375 0.50411625]
[0.49620063 0.50379937]
[0.49626537 0.50373463]
[0.49607432 0.50392568]
[0.49607219 0.50392781]
[0.49540239 0.50459761]
[0.49564292 0.50435708]
[0.4954833 0.5045167]
[0.4959788 0.5040212]
[0.49609633 0.50390367]
[0.49620411 0.50379589]
[0.49571376 0.50428624]
[0.49535542 0.50464458]
[0.4956498 0.5043502]
[0.49601105 0.50398895]
[0.49619252 0.50380748]
[0.49596926 0.50403074]
[0.49612194 0.50387806]
[0.49593476 0.50406524]
[0.49600868 0.50399132]
[0.49590174 0.50409826]
[0.49577817 0.50422183]
[0.49611243 0.50388757]
[0.49618401 0.50381599]
[0.49581876 0.50418124]
[0.4958551 0.5041449]
[0.49624129 0.50375871]
[0.49599038 0.50400962]
[0.49631314 0.50368686]
[0.49597163 0.50402837]
[0.49568928 0.50431072]
[0.49608036 0.50391964]
[0.49571931 0.50428069]
[0.49613709 0.50386291]
[0.4961094 0.5038906]
[0.4955773 0.5044227]
[0.49624335 0.50375665]
[0.49610305 0.50389695]
[0.49626953 0.50373047]
[0.49622376 0.50377624]
[0.49607923 0.50392077]
[0.4

In [20]:
0 in y_pred[:,0]

False

In [21]:
y_pred[:,0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [22]:
print(y_pred_proba)

[[[0.49609863]
  [0.50390137]]

 [[0.49588375]
  [0.50411625]]

 [[0.49620063]
  [0.50379937]]

 ...

 [[0.49576033]
  [0.50423967]]

 [[0.49595471]
  [0.50404529]]

 [[0.49595775]
  [0.50404225]]]


In [23]:
y_test

array([[[1],
        [0]],

       [[1],
        [0]],

       [[1],
        [0]],

       ...,

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [0]]])

In [24]:
y_test.argmax(axis=1)[:,0]

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,

In [25]:
x_test.iloc[-1]

meanfreq    0.187154
sd          0.060350
median      0.167518
Q25         0.139799
Q75         0.252281
IQR         0.112482
kurt        8.442947
sp.ent      0.892330
sfm         0.389373
mode        0.253888
meanfun     0.141512
minfun      0.047856
modindx     0.123510
Name: 1188, dtype: float64

In [26]:
nn.a_values[-1][1:]

array([[0.49595775],
       [0.50404225]])