In [36]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from NeuralNetwork import *
import warnings
warnings.filterwarnings("ignore")

In [37]:
df = pd.read_csv('../../../ML-Project/assests/feature_selected_voice_data.csv')

In [38]:
df = df.sample(frac=1)
df

meanfreq        sd    median       Q25       Q75       IQR       kurt  \
1127  0.182041  0.064755  0.167383  0.137686  0.243747  0.106061   5.891027   
789   0.173225  0.057845  0.189989  0.117108  0.218643  0.101535   5.511006   
2886  0.209168  0.043454  0.213612  0.188229  0.237043  0.048815   6.776005   
2914  0.231191  0.030978  0.234063  0.214922  0.249375  0.034453   5.099258   
429   0.186898  0.056797  0.213243  0.125405  0.229189  0.103784  10.736947   
...        ...       ...       ...       ...       ...       ...        ...   
1389  0.199629  0.055893  0.225206  0.139749  0.246320  0.106571   8.937920   
931   0.185769  0.057848  0.183956  0.130091  0.236806  0.106715  11.945638   
7     0.160514  0.076767  0.144337  0.110532  0.231962  0.121430   4.766611   
734   0.170136  0.060067  0.181679  0.109435  0.218870  0.109435   5.896739   
2355  0.244356  0.031809  0.252995  0.231675  0.265787  0.034112   8.115037   

        sp.ent       sfm      mode   meanfun    minfun   modindx   label  
1127  0.927975  0.536623  0.278072  0.127216  0.047478  0.134277    male  
789   0.921118  0.434304  0.211168  0.108406  0.019925  0.280718    male  
2886  0.875890  0.296413  0.210098  0.163228  0.047384  0.152618  female  
2914  0.825663  0.143724  0.243359  0.193043  0.050473  0.140504  female  
429   0.896890  0.383985  0.218378  0.114696  0.022663  0.230100    male  
...        ...       ...       ...       ...       ...       ...     ...  
1389  0.871339  0.259785  0.242801  0.131037  0.049434  0.155440    male  
931   0.886244  0.322637  0.233249  0.121225  0.047013  0.103133    male  
7     0.959255  0.719858  0.128324  0.093052  0.017758  0.283937    male  
734   0.908573  0.437560  0.109435  0.095223  0.018735  0.091431    male  
2355  0.808986  0.114351  0.253942  0.174934  0.047809  0.086462  female  

[3168 rows x 14 columns]

In [39]:
df['label'].unique()

array(['male', 'female'], dtype=object)

In [40]:
x = df.drop('label' , axis=1)
# y = label_binarize(df['label'], classes=df['label'].unique())
y = []
for i in range(x.shape[0]):
    y.append(np.array([[1], [0]]) if df.iloc[i]['label']=='male' else np.array([[0],[1]]))
y = np.array(y)

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [42]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2534, 13)
(634, 13)
(2534, 2, 1)
(634, 2, 1)


In [43]:
y_train[:10]

array([[[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[1],
        [0]]])

### Neural Network

In [44]:
nn = NeuralNetwork(4, [13,128,64,2], 1e-3, 'sigmoid', 'random', 100, 100)

In [45]:
print(nn.a_values)

[array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]) array([[1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
      

In [46]:
nn.forwardPropagation(x_train.iloc[0])

array([[0.74650145],
       [0.25349855]])

In [47]:
# nn.backwardPropagation(np.array([0,1]))

In [48]:
print(nn.a_values)

[array([[1.        ],
        [0.20015819],
        [0.03700272],
        [0.20263158],
        [0.185     ],
        [0.22421053],
        [0.03921053],
        [9.68773293],
        [0.86104489],
        [0.25636655],
        [0.20026316],
        [0.17423854],
        [0.01948843],
        [0.13641975]]) array([[1.00000000e+00],
                              [1.30898733e-01],
                              [3.46408643e-04],
                              [5.96275934e-02],
                              [4.51675717e-03],
                              [4.03628737e-01],
                              [9.96165739e-01],
                              [9.30327977e-01],
                              [4.52718001e-04],
                              [9.81149541e-01],
                              [4.56136242e-05],
                              [1.52656492e-03],
                              [7.38874468e-02],
                              [2.45891973e-04],
                              [1.31621361e

In [49]:
print(nn.weights_Θ[0].shape)
print(nn.weights_Θ[1].shape)
print(nn.weights_Θ[2].shape)
print(nn.epochs)
print(nn.lr)
print(nn.activation)

(32, 14)
(32, 33)
(2, 33)
100
0.001


In [50]:
nn.δ_values[3][1:]

array([[1.],
       [1.]])

In [51]:
nn.fit(x_train, y_train)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [52]:
y_pred_proba = nn.predict_proba(x_test)
nn.score(x_test, y_test)

0.7397476340694006

In [53]:
for _ in y_pred_proba:
    print(_[:,0])

[0.50078527 0.49921473]
[0.54805973 0.45194027]
[0.50630627 0.49369373]
[0.29844767 0.70155233]
[0.90814008 0.09185992]
[0.64829209 0.35170791]
[0.44446158 0.55553842]
[0.91777675 0.08222325]
[0.50696956 0.49303044]
[0.78429521 0.21570479]
[0.22069858 0.77930142]
[0.38477575 0.61522425]
[0.93035248 0.06964752]
[0.47607514 0.52392486]
[0.4477798 0.5522202]
[0.71604815 0.28395185]
[0.62323349 0.37676651]
[0.87761066 0.12238934]
[0.56947986 0.43052014]
[0.33856981 0.66143019]
[0.37957981 0.62042019]
[0.3748922 0.6251078]
[0.26350421 0.73649579]
[0.38053902 0.61946098]
[0.85831145 0.14168855]
[0.21305015 0.78694985]
[0.55311685 0.44688315]
[0.48799537 0.51200463]
[0.25415596 0.74584404]
[0.3854313 0.6145687]
[0.46316753 0.53683247]
[0.9549212 0.0450788]
[0.25372833 0.74627167]
[0.21615302 0.78384698]
[0.35016937 0.64983063]
[0.46531752 0.53468248]
[0.30570862 0.69429138]
[0.32553468 0.67446532]
[0.75644242 0.24355758]
[0.29960957 0.70039043]
[0.89324389 0.10675611]
[0.33306607 0.66693393]


In [54]:
0 in y_pred[:,0]

True

In [55]:
y_pred[:,0]

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,

In [56]:
print(y_pred_proba)

[[[0.50078527]
  [0.49921473]]

 [[0.54805973]
  [0.45194027]]

 [[0.50630627]
  [0.49369373]]

 ...

 [[0.27636612]
  [0.72363388]]

 [[0.24941228]
  [0.75058772]]

 [[0.37860895]
  [0.62139105]]]


In [57]:
y_test

array([[[1],
        [0]],

       [[1],
        [0]],

       [[1],
        [0]],

       ...,

       [[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]]])

In [58]:
y_test.argmax(axis=1)[:,0]

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,

In [59]:
x_test.iloc[-1]

meanfreq    0.193205
sd          0.056827
median      0.196949
Q25         0.145932
Q75         0.237288
IQR         0.091356
kurt        9.373751
sp.ent      0.914533
sfm         0.226079
mode        0.000000
meanfun     0.129797
minfun      0.044944
modindx     0.142722
Name: 306, dtype: float64

In [60]:
nn.a_values[-1][1:]

array([[0.37860895],
       [0.62139105]])