In [46]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from NeuralNetwork import *
import warnings
warnings.filterwarnings("ignore")

In [47]:
df = pd.read_csv('../../../ML-Project/assests/feature_selected_voice_data.csv')

In [48]:
df = df.sample(frac=1)
df

meanfreq        sd    median       Q25       Q75       IQR        kurt  \
1727  0.147401  0.087014  0.179663  0.052884  0.218397  0.165513    4.626268   
1997  0.176375  0.089545  0.205757  0.111365  0.249916  0.138551   21.795893   
1760  0.181565  0.037959  0.175561  0.165455  0.198396  0.032941   12.867535   
1109  0.182813  0.058998  0.162857  0.137959  0.237551  0.099592    4.698105   
363   0.139583  0.078500  0.127212  0.092295  0.212836  0.120540    9.481440   
...        ...       ...       ...       ...       ...       ...         ...   
2914  0.231191  0.030978  0.234063  0.214922  0.249375  0.034453    5.099258   
280   0.165368  0.074977  0.190579  0.105960  0.226433  0.120473  328.195982   
2164  0.185120  0.041638  0.185397  0.173651  0.209524  0.035873   13.623543   
972   0.198937  0.063053  0.224000  0.133538  0.261812  0.128274    8.167890   
2025  0.186188  0.059803  0.195726  0.173183  0.227118  0.053935    7.227563   

        sp.ent       sfm      mode   meanfun    minfun   modindx   label  
1727  0.960339  0.705241  0.060031  0.181477  0.022695  0.113007  female  
1997  0.938456  0.557869  0.000000  0.196777  0.043716  0.288079  female  
1760  0.853810  0.295184  0.171070  0.164493  0.021563  0.111368  female  
1109  0.917399  0.414762  0.140816  0.137282  0.047809  0.179363    male  
363   0.964500  0.755740  0.115203  0.096002  0.027350  0.295775    male  
...        ...       ...       ...       ...       ...       ...     ...  
2914  0.825663  0.143724  0.243359  0.193043  0.050473  0.140504  female  
280   0.946306  0.620250  0.000000  0.118109  0.031250  0.186526    male  
2164  0.855730  0.305585  0.180952  0.189023  0.111111  0.101836  female  
972   0.870830  0.259881  0.267077  0.131275  0.048000  0.022487    male  
2025  0.922318  0.530253  0.193830  0.172243  0.022890  0.200746  female  

[3168 rows x 14 columns]

In [49]:
df['label'].unique()

array(['female', 'male'], dtype=object)

In [50]:
x = df.drop('label' , axis=1)
# y = label_binarize(df['label'], classes=df['label'].unique())
y = []
for i in range(x.shape[0]):
    y.append(np.array([[1], [0]]) if df.iloc[i]['label']=='male' else np.array([[0],[1]]))
y = np.array(y)

In [51]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [52]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2534, 13)
(634, 13)
(2534, 2, 1)
(634, 2, 1)


In [53]:
y_train[:10]

array([[[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]],

       [[1],
        [0]],

       [[1],
        [0]],

       [[0],
        [1]]])

### Neural Network

In [54]:
nn = NeuralNetwork(4, [13,128,64,2], 1e-3, 'sigmoid', 'random', 200, 100)

In [55]:
print(nn.a_values)

[array([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]]) array([[1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
                      [1.],
      

In [56]:
nn.forwardPropagation(x_train.iloc[0])

array([[0.03320921],
       [0.96679079]])

In [57]:
print(nn.a_values)

[array([[1.        ],
        [0.19233982],
        [0.05894536],
        [0.20063694],
        [0.14      ],
        [0.24135881],
        [0.10135881],
        [3.04523637],
        [0.93067936],
        [0.42520123],
        [0.272569  ],
        [0.13424415],
        [0.04692082],
        [0.11545679]]) array([[1.        ],
                              [0.97681681],
                              [0.96108695],
                              [0.7168392 ],
                              [0.26515456],
                              [0.54412435],
                              [0.11101133],
                              [0.90163773],
                              [0.87154179],
                              [0.94513443],
                              [0.85758332],
                              [0.79393987],
                              [0.89892114],
                              [0.19991842],
                              [0.08897553],
                              [0.12213287],
          

In [58]:
print(nn.weights_Θ[0].shape)
print(nn.weights_Θ[1].shape)
print(nn.weights_Θ[2].shape)
print(nn.epochs)
print(nn.lr)
print(nn.activation)

(128, 14)
(64, 129)
(2, 65)
200
0.001


In [59]:
nn.δ_values[3][1:]

array([[1.],
       [1.]])

In [60]:
nn.fit(x_train, y_train)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 

In [61]:
y_pred = nn.predict(x_test)
y_pred_proba = nn.predict_proba(x_test)
print(nn.score(x_train, y_train))
print(nn.score(x_test, y_test))

0.9214680347277032
0.9321766561514195


In [62]:
for _ in y_pred_proba:
    print(_[:,0])

[0.82368327 0.17631673]
[0.01253712 0.98746288]
[0.10696292 0.89303708]
[0.93800881 0.06199119]
[0.0836721 0.9163279]
[0.8794677 0.1205323]
[0.5672681 0.4327319]
[0.43341424 0.56658576]
[0.02498128 0.97501872]
[0.82789395 0.17210605]
[0.89970206 0.10029794]
[0.86706356 0.13293644]
[0.14008679 0.85991321]
[0.276796 0.723204]
[0.87799948 0.12200052]
[0.88712319 0.11287681]
[0.46526648 0.53473352]
[0.02458325 0.97541675]
[0.07422917 0.92577083]
[0.06927411 0.93072589]
[0.07328012 0.92671988]
[0.23227381 0.76772619]
[0.96816907 0.03183093]
[0.89703997 0.10296003]
[0.15382488 0.84617512]
[0.91571389 0.08428611]
[0.02940027 0.97059973]
[0.96894382 0.03105618]
[0.03908857 0.96091143]
[0.95693426 0.04306574]
[0.82672986 0.17327014]
[0.65463113 0.34536887]
[0.7147977 0.2852023]
[0.00323874 0.99676126]
[0.84986466 0.15013534]
[0.14152592 0.85847408]
[0.13457265 0.86542735]
[0.86151171 0.13848829]
[0.71474985 0.28525015]
[0.52860986 0.47139014]
[0.8235722 0.1764278]
[0.85345974 0.14654026]
[0.916

In [63]:
0 in y_pred[:,0]

True

In [64]:
y_pred[:,0]

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,

In [65]:
print(y_pred_proba)

[[[0.82368327]
  [0.17631673]]

 [[0.01253712]
  [0.98746288]]

 [[0.10696292]
  [0.89303708]]

 ...

 [[0.88029104]
  [0.11970896]]

 [[0.49338656]
  [0.50661344]]

 [[0.6719717 ]
  [0.3280283 ]]]


In [66]:
y_test

array([[[1],
        [0]],

       [[0],
        [1]],

       [[0],
        [1]],

       ...,

       [[1],
        [0]],

       [[0],
        [1]],

       [[1],
        [0]]])

In [67]:
y_test.argmax(axis=1)[:,0]

array([0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,

In [68]:
x_test.iloc[-1]

meanfreq    0.179178
sd          0.062323
median      0.186475
Q25         0.126803
Q75         0.225492
IQR         0.098689
kurt        4.077164
sp.ent      0.940103
sfm         0.568020
mode        0.210000
meanfun     0.134829
minfun      0.047904
modindx     0.158600
Name: 1450, dtype: float64

In [69]:
nn.a_values[-1][1:]

array([[0.6719717],
       [0.3280283]])